---
- name: "Install apache2 package"
  apt:
    name: "apache2"
    state: "latest"
    update_cache: True

- name: "Make sure apache2 is started"
  service:
    name: "apache2"
    state: "started"
    enabled: True
...
