---
- hosts: web
  become: True
  roles:
    - apache2
    - php
  tasks:
    - name: "Remove default index.html"
      file:
        path: "/var/www/html/index.html"
        state: absent
    - name: "Copy index.php"
      copy:
        src: "index.php"
        dest: "/var/www/html/"
...
